if ARGV.include? "-h"
    puts "Hello World!"
    puts "This GBM Helper can help you imporve your build with features such as:"
    puts "  - View my current build:"
    puts "          The parts you are currently using will be displayed in a table and the value of each attribute will be summed up for you."
    puts "  - Start a new build:"
    puts "          ONLY if you want to start a new build from scratch so be careful"
    puts "  - Search parts by name:"
    puts "          If you know what you are looking for, you can simply search for it by name."
    puts "          If the part is altered, remember to puy altered in front of the Gundam name in your search."
    puts "  - Filter and sort parts:"
    puts "          If you are not sure what to use, you can try filter by category and sort by attribute feature to find parts that might help you."
    puts "  - Ger a build recommendation:"
    puts "        > I am looking for parts with the highest attribute and a certain type:"
    puts "                  This can be a good place to both start your build and finalise your build." 
    puts "                  The part with the higheset attribute in each category will be displayed in a table."
    puts "        > I am looking for pilots with a certain job license and type:"
    puts "                  This feature can help you find the right pilot for your customised Gundam."
    puts "                  If you are building a fighter, you might want to choose either In-Fighter or Out-Fighter."
    puts "                  If you are building a Shooter, you might want to choose either Middle-Shooter or Long-Shooter."
    puts "        > I am looking for parts with a certain word tag and type:"
    puts "                  Word tags when activated can improve your attributes."
    puts "                  This feature will quickly help you find the parts with the right word tags."
    puts "  - Log out:"
    puts "          Your build is ONLY saved when you log out so don't forget to log out."
    puts ""
    puts "Command to find out the current version"
    puts "  -v"
    exit
end

if ARGV.include? "-v"
    puts "version 1.1.1"
    exit
end