# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "bundler"
gem "tty-prompt"
gem "tty-table"
gem "colorize"
gem "ruby_figlet"
gem "lolcat"
gem "lolize"
gem "test-unit", "~> 3.4"
